const data = {
  products: [

      {
          name: 'Nike Slim shirt',
          slug: 'nike-slim-shirt',
          category: 'Shirts',
          image: '/images/p1.jpg', // 679px × 829px
          price: 120,
          countInStock: 10,
          brand: 'Nike',
          rating: 4.5,
          numReviews: 10,
          description: 'high quality shirt',
        },
        {
          name: 'Adidas Fit Shirt',
          slug: 'adidas-fit-shirt',
          category: 'Shirts',
          image: '/images/p2.jpg',
          price: 250,
          countInStock: 20,
          brand: 'Adidas',
          rating: 4.0,
          numReviews: 10,
          description: 'high quality product',
        },
        {
          name: 'Nike bjkiji Pant',
          slug: 'jkhio',
          category: 'Pants',
          image: '/images/p3.jpg',
          price: 25,
          countInStock: 15,
          brand: 'Nike',
          rating: 4.5,
          numReviews: 14,
          description: 'high quality product',
        },
        {
          name: 'Adidas m nrtrttbjkjk Pant',
          slug: 'adidajkbjkrtrthnt',
          category: 'Pants',
          image: '/images/p4.jpg',
          price: 65,
          countInStock: 5,
          brand: 'Puma',
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
    {

      
      name: 'T shirt',
      slug: 'T shirt',
      category: 'Shirts',
      image: '/images/dd.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidrttas Fit Shirt',
      slug: 'adidftrtas-fit-shirt',
      category: 'Shirts',
      image: '/images/fh.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Shirt',
      slug: 'fit size',
      category: 'Shirts',
      image: '/images/GojoRunningHoodie.png',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike bttttrtfdjkiji Pant',
      slug: 'jktthio',
      category: 'Pants',
      image: '/images/ttt.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas m nbjerekjk Pant',
      slug: 'adidajkbjkhnt',
      category: 'Pants',
      image: '/images/rg.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas jbbjherrru Pant',
      slug: 'n bjkbjk-fit-pant',
      category: 'Pants',
      image: '/images/dt.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quambjkjkkjlity product',
    },
    {
      name: 'gbgjgkkjg',
      slug: 'fklfhkpkph',
      category: 'Shoes',
      image: '/images/ryy.jpg', // 679px × 829px
      price: 145,
      countInStock: 0,
      brand: 'bu',
      rating: 4.5,
      numReviews: 10,
      description: '',
    },

    {
      name: 'hjm ',
      slug: 'nmkmom',
      category: 'Shoes',
      image: '/images/ggdg.jpg', 
      price: 140,
      countInStock: 0,
      brand: 'gyg',
      rating: 3.5,
      numReviews: 100,
      description: 'moutyoo',
    },
    {
      name: 'hjmf ',
      slug: 'nmkmomr',
      category: 'Shoes',
      image: '/images/fgdft.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gyg',
      rating: 3.5,
      numReviews: 100,
      description: 'mogtuoo',
    },
    {
      name: 'dell ',
      slug: 'nmkmtrtiomrfhbb',
      category: 'Computers',
      image: '/images/ryuu.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gyg',
      rating: 3.5,
      numReviews: 100,
      description: 'mouttoo',
    },
    {
      name: 'acer ',
      slug: 'nmkmomrrtrtfhbb',
      category: 'Computers',
      image: '/images/gfxg.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gyggh',
      rating: 3.5,
      numReviews: 100,
      description: 'mouoro',
    },{
      name: 'Apple ',
      slug: 'nmkmomrjknttoifhbb',
      category: 'Computers',
      image: '/images/gfdgf.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gygttyyy',
      rating: 3.5,
      numReviews: 100,
      description: 'mouyoto',
    },

    {
      name: 'Appleyye ',
      slug: 'nmkmttyyomrfhbb',
      category: 'Watches',
      image: '/images/ffff.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gygyyy',
      rating: 3.5,
      numReviews: 100,
      description: 'mouyootty',
    },
    {
      name: 'ROLEX',
      slug: 'nmkmomrtjtfhbb',
      category: 'Watches',
      image: '/images/ffdfdfs.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gygtyyy',
      rating: 3.5,
      numReviews: 100,
      description: 'good',
    },
    {
      name: 'FYTYRTU',
      slug: 'nmkmomrhhtfhbb',
      category: 'Watches',
      image: '/images/dffsf.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gygjyyy',
      rating: 3.5,
      numReviews: 100,
      description: 'ghoo',
    },
    {
      name: 'tre',
      slug: 'nmkmomrfhbb',
      category: 'TOYS',
      image: '/images/downloadffff.jpg', 
      price: 0,
      countInStock: 100,
      brand: 'gygryyy',
      rating: 3.5,
      numReviews: 100,
      description: 'tyg',
    },
    {
      name: 'trrgefry',
      slug: 'nmkmomriiiofherbb',
      category: 'TOYS',
      image: '/images/dfd.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'grrygyeyy',
      rating: 3.5,
      numReviews: 100,
      description: 'teyg',
    },
    {
      name: 'trefrdrdy',
      slug: 'nmkmomdddrfherbb',
      category: 'TOYS',
      image: '/images/dfffsf.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gygyeyy',
      rating: 3.5,
      numReviews: 100,
      description: 'ttredyg',
    },
    {
      name: 'trefrferdfdy',
      slug: 'nmkmobb',
      category: 'Grocery',
      image: '/images/ssssssssssst.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gyegyeyy',
      rating: 3.5,
      numReviews: 100,
      description: 'tefedyg',
    },
    {
      name: 'trefrdfdy',
      slug: 'nmkmomrrdddrfherbbggll',
      category: 'Shirts',
      image: '/images/sdffs.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gyegydeyy',
      rating: 3.5,
      numReviews: 100,
      description: 'tggeedyg',
    },

    {
      name: 'dtkljoyt',
      slug: 'nlll',
      category: 'Grocery',
      image: '/images/downloaddffsf.jpg', 
      price: 140,
      countInStock: 100,
      brand: 'gyegyeyy',
      rating: 3.5,
      numReviews: 100,
      description: 'teevvdyg',
    },
    {
      name:'Lock',
      slug:'ieiie',
      category:' Grocery',
      image: '/images/downloaddffsf.jpg', 
      price:500,
      brand:'dhfhhfhk',
      rating:4.5,
      numReviews:400,
      discription:'rhyurttuhjrtr'

    }
    
  ],
};
export default data;
